name: NPM publish

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tsc_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install dependencies
        run: yarn

      - name: Typechecking
        run: yarn tsc

      - name: Test
        run: yarn test

  publish-npm:
    needs: tsc_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish
        working-directory: pkg
        run: yarn publish --access public
